### 异常处理

#### 异常概述

很多问题不是靠代码能够避免的，比如：客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅等等。



异常：在Java语言中，将程序执行中发生的不正常情况称为"异常"。

分为两类：
Error：Java虚拟机无法解决的严重问题：JVM系统内部错误、资源耗尽。一般不编写针对性代码进行处理。



Exception：其他因编程错误或偶然的外在因素导致的一般性问题，可以用针对性代码进行处理：

空指针访问

试图读取不存在的文件

网络连接中断

数组角标越界

对于这些错误，一般有两种解决方法：一是遇到错误就终止程序运行。

​						一种是在编写程序时，就考虑到错误的检查，错误消息的提示，以及错误的处理。

分类：编译时异常和运行时异常



#### 异常体系结构

java.lang.Throwable

​		|---------java.lang.Error：一般不编写针对性的代码进行处理。

​		|---------java.lang.Exception: 可以进行异常的处理

​				|----------编译时异常(checked)

​								|----------IOException

​											|---------FileNotFoundException

​								|-----------ClassNotFoundException

​				|----------运行时异常(unchecked,RuntimeException)

​								|-----------NullPointerException

​								|-----------ArrayIndexOutOfBoundsException

​								|-----------ClassCastException

​								|-----------NumberFormatException

​								|-----------InputMismatchException

​								|-----------ArithmeticException



面试题：常见的异常都有哪些？举例说明

##### 常见异常类型

运行时异常

NullPointerException		空指针异常，对象指向的地址为空

ArrayIndexOutOfBoundsException	数组下标越界

StringIndexOutOfBoundsException	字符串下标越界

ClassCastException								类型转换异常

NumberFormatException					数字格式化异常，字符串中夹杂其他类型

InputMismatchException					输入不匹配

ArithmeticException							算数异常 分子是0



#### 异常处理机制

抓抛模型

过程一：“抛”：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象。并将此对象抛出。

​			一旦抛出对象以后，其后的代码就不再执行。跳出try包裹的代码

​					1.系统自动生成的异常对象	2.手动的生成异常对象，并抛出(throw)



过程二：“抓”：异常的处理方式：1.try-catch-finally  2.throws



##### try-catch-finally

try{

​		//可能出现异常的代码

}catch(异常类型1	变量名1){

​		//处理异常方式1

}catch(异常类型2	变量名2){

​		//处理异常方式2

}catch(异常类型3	变量名3){

​		//处理异常方式3

}

.	.	.	.

finally{

​	//一定会执行的代码

}

说明：

1.finally是可选的。

2.使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配。

3.一旦try中的异常对象匹配到某一catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构(在没有写finally的情况)。继续执行其后的代码

4.catch中的异常类型没有子父类关系，声明位置无所谓。子类的声明在父类上面。(因为多态性)

5.常用的异常对象处理的方式：1.String getMessage()	2.printStackTrace()

6.在try结构中声明的变量，出了try结构之后，不能再被调用。

7.try-catch-finally可以嵌套



使用try-catch-finally将异常延后到运行时报错。

开发中，由于运行时异常比较常见，所有我们通常不针对运行时异常编写try-catch-finally

针对编译时异常，一定要考虑异常的处理。



finally

1.finally中声明的是一定会被执行的代码，即使catch中又出现异常了，try和catch中有return语句等情况。

2.像数据库连接，输入输出流，网络编程Socket等资源，JVM是不能自动回收的，我们需要手动的进行资源的释放，就需要声明再finally中。



如果finally中没有return语句，但是改变了要返回的值，分以下两种情况：
如果return的是基本数据类型或引用类型，则在finally中对值或引用的改变不起作用，try中的return语句依然会返回之前保留的值。
如果return的是引用类型，而在finally中修改该引用类型的属性值，try中return语句返回的对象，属性值是finally中改变后的属性值。



##### throws + 异常类型

```java
public class FinallyTest {

    public static void main(String[] args) {
        try {
            method2();
        }catch (IOException e){
            e.printStackTrace();
        }
    }
    
    public static void method2() throws IOException{
        methods1();
    }

    public static void methods1() throws FileNotFoundException, IOException {
        File file = new File("Hello.txt");
        FileInputStream fis = new FileInputStream(file);

        int data = fis.read();
        while (data != -1){
            System.out.println((char) data);
            data = fis.read();
        }

        fis.close();
    }
}
```

写在方法的声明处，指明此方法执行时，可能会抛出的异常类型。

一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！



try-catch-finally:真正的将异常给处理掉了

thorws只是将异常传给了调用者，没有实际解决异常



#### 如何选择异常处理

1.如果父类被重写的方法没有throws方式处理异常，则子类也不能使用throws。

2.执行的方法a中，先后有调用了另外的几个方法，这几个方法是递进关系执行的。用throws的方式进行处理，而执行方法a中可以使用try-catch-finally方式进行处理





#### 手动抛出异常

throw new RuntimeException("");



#### 自定义异常类

 1.定义与现有的异常结构：RuntimeException、Exception。

2.提供全局常量，serialVersionUID

3.提供重载的构造器

```java
public class MyException extends RuntimeException{
    static final long serialVersionUID = -70348971907939L;

    public MyException() {
    }

    public MyException(String message) {
        super(message);
    }
}
```